### ISSUE TITLE
Optimise dependencies

### ISSUE THREAD

**Issue by thompson-tomo** [fluxera/Fluxera.Enumeration#49]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want the package to not have an explicit dependency on System.Text.Json as it can be provided by the framework when targeting net 6. JetBrains.Annotatons should also be a dev dependency.

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by mgernand** [comment]
Hi! Thanks for this proposal. We'll look into it.

**Comment by mgernand** [comment]
- Referenced JetBrains.Annotations as dev dependency.
- Removed explicit reference to System.Text.Json.
